apiVersion: datapower.ibm.com/v1beta3
kind: DataPowerService
metadata:
  name: quickstart
  labels:
    backup.datapower.ibm.com/component: datapowerservice
  namespace: nfcu-demo
spec:
  license:
    accept: true
    license: L-MBWD-G64ATA
    use: nonproduction
  resources:
    limits:
      memory: 4Gi
    requests:
      cpu: 1
      memory: 4Gi
  users:
    - accessLevel: privileged
      name: admin
      passwordSecret: dp-admin-password
  domains:
    - certs:
        - certType: sharedcerts
          secret: github.com.cer
      dpApp:
        config:
          - web-mgmt-cfg
      name: default
    - certs:
        - certType: sharedcerts
          secret: github.com.cer      
      name: demo
    - certs:
        - certType: sharedcerts
          secret: github.com.cer      
      name: Test  
  replicas: 1
  storage:
    - type: persistent
      path: /opt/ibm/datapower/drouter/config
      size: 5Gi
      class: local-file-sc
      volumeMode: Filesystem
      deleteClaim: false          # <--- CRITICAL: Prevents OCP from deleting the PVC on rebuilds
    - type: persistent
      path: /opt/ibm/datapower/drouter/local
      size: 1Gi
      class: local-file-sc
      volumeMode: Filesystem
      deleteClaim: false          # <--- CRITICAL: Prevents OCP from deleting the PVC on rebuilds
    - type: ephemeral
      path: /opt/ibm/datapower/drouter/temporary
      size: 1Gi
  version: 11.0.0.1