apiVersion: datapower.ibm.com/v1beta3
kind: DataPowerService
metadata:
  creationTimestamp: '2026-07-09T14:31:42Z'
  generation: 1
  labels:
    backup.datapower.ibm.com/component: datapowerservice
  managedFields:
    - apiVersion: datapower.ibm.com/v1beta3
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            .: {}
            'f:backup.datapower.ibm.com/component': {}
        'f:spec':
          .: {}
          'f:domains': {}
          'f:hostAliases': {}
          'f:license':
            .: {}
            'f:accept': {}
            'f:license': {}
            'f:use': {}
          'f:replicas': {}
          'f:resources':
            .: {}
            'f:limits':
              .: {}
              'f:memory': {}
            'f:requests':
              .: {}
              'f:cpu': {}
              'f:memory': {}
          'f:users': {}
          'f:version': {}
      manager: Mozilla
      operation: Update
      time: '2026-07-09T14:31:42Z'
    - apiVersion: datapower.ibm.com/v1beta3
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:pods': {}
          'f:phase': {}
          'f:conditions': {}
          .: {}
          'f:firmware': {}
          'f:versions':
            .: {}
            'f:available':
              .: {}
              'f:channels': {}
              'f:versions': {}
            'f:reconciled': {}
          'f:replicas': {}
          'f:mgmtPorts': {}
          'f:customImages': {}
          'f:labelSelector': {}
      manager: datapower-operator
      operation: Update
      subresource: status
      time: '2026-07-09T15:40:47Z'
  name: quickstart
  namespace: nfcu-demo
  resourceVersion: '11904079'
  uid: 3d16152e-01f9-4918-a00a-e82ac0984f9c
spec:
  license:
    accept: true
    license: L-MBWD-G64ATA
    use: nonproduction
  cryptoMode: permissive
  resources:
    limits:
      cpu: '1'
      memory: 4Gi
    requests:
      cpu: '1'
      memory: 4Gi
  readinessProbe:
    failureThreshold: 3
    httpGet:
      path: /healthz
      port: 7879
      scheme: HTTP
    initialDelaySeconds: 10
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 5
  users:
    - accessLevel: privileged
      name: admin
      passwordSecret: dp-admin-password
  terminationGracePeriodSeconds: 30
  healthCheck:
    logLevel: info
    probe:
      port: 7879
    watchdog:
      enabled: true
      hardTimeoutSeconds: 80
      softTimeoutSeconds: 60
  createServiceBinding: automatic
  livenessProbe:
    failureThreshold: 3
    httpGet:
      path: /healthz
      port: 7879
      scheme: HTTP
    initialDelaySeconds: 10
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 5
  domains:
    - certs:
        - certType: sharedcerts
          secret: github.com.cer
      dpApp:
        config:
          - web-mgmt-cfg
      name: default
    - certs:
        - certType: sharedcerts
          secret: github.com.cer
      dpApp:
        config:
          - pull-from-git-cfg
      name: demo
      passwordMap:
        - alias: pat
          secret: pat
    - certs:
        - certType: sharedcerts
          secret: github.com.cer
      dpApp:
        config:
          - pull-from-git-cfg
      name: Test
      passwordMap:
        - alias: pat
          secret: pat     
  imagePullPolicy: IfNotPresent
  hostAliases:
    - hostnames:
        - loopback
      ip: 127.0.0.1
  version: 11.0.0.1
  podManagementPolicy: Parallel
  replicas: 1
  rbm:
    passwordHashAlgorithm: sha256
  snmp:
    exporter:
      enabled: false
status:
  customImages: false
  pods:
    - quickstart-0
  mgmtPorts:
    - name: rest-mgmt
      port: 5554
  labelSelector: 'app.kubernetes.io/instance=nfcu-demo-quickstart,app.kubernetes.io/name=datapower'
  conditions:
    - lastTransitionTime: '2026-07-09T15:40:01Z'
      message: 'StatefulSet replicas ready: 1/1'
      reason: StatefulSetReady
      status: 'True'
      type: Ready
  phase: Running
  firmware:
    - info:
        build: '384502'
        buildDate: '2026/04/27 19:00:26'
        version: IDG.11.0.0.1
      pods:
        - quickstart-0
  versions:
    available:
      channels:
        - licenses:
            - displayName: IBM DataPower Gateway Virtual Edition v11.0.0
              link: 'https://ibm.biz/Bdb59j'
              matchesCurrentType: true
              name: L-MBWD-G64ATA
            - displayName: IBM DataPower Gateway Developers for Docker v11.0.0
              link: 'https://ibm.biz/Bdb59Z'
              matchesCurrentType: false
              name: L-PDSS-XG3B9H
          name: 11.0-sc2
      versions:
        - licenses:
            - displayName: IBM DataPower Gateway Virtual Edition v11.0.0
              link: 'https://ibm.biz/Bdb59j'
              matchesCurrentType: true
              name: L-MBWD-G64ATA
            - displayName: IBM DataPower Gateway Developers for Docker v11.0.0
              link: 'https://ibm.biz/Bdb59Z'
              matchesCurrentType: false
              name: L-PDSS-XG3B9H
          name: 11.0.0.2
        - licenses:
            - displayName: IBM DataPower Gateway Virtual Edition v11.0.0
              link: 'https://ibm.biz/Bdb59j'
              matchesCurrentType: true
              name: L-MBWD-G64ATA
            - displayName: IBM DataPower Gateway Developers for Docker v11.0.0
              link: 'https://ibm.biz/Bdb59Z'
              matchesCurrentType: false
              name: L-PDSS-XG3B9H
          name: 11.0.0.1sr1
        - licenses:
            - displayName: IBM DataPower Gateway Virtual Edition v11.0.0
              link: 'https://ibm.biz/Bdb59j'
              matchesCurrentType: true
              name: L-MBWD-G64ATA
            - displayName: IBM DataPower Gateway Developers for Docker v11.0.0
              link: 'https://ibm.biz/Bdb59Z'
              matchesCurrentType: false
              name: L-PDSS-XG3B9H
          name: 11.0.0.1
    reconciled: 11.0.0.1
  replicas: 1
